### ISSUE TITLE
Maths/rounding error?

### ISSUE THREAD

**Issue by gingerbeardman** [picolove/picolove#1]
I wonder if this is a maths/rounding error?

code (called with integer values)

``` lua
function draw_card(s,x,y)
  spr(s, x,y, 2,2) -- main sprite
  line(x+1,y-1, x+14,y-1) -- top edge
  line(x+1,y+16, x+14,y+16) -- btm edge
end
```

Interesting that only one of the two lines is drawn in the wrong place? Both coordinates are 1px out vertically.

Also, badly mapped/missing = (equals) sign in font?

compare
![picoLove screenshot](https://cloud.githubusercontent.com/assets/49612/9771852/9ff4ff0c-5730-11e5-9643-b5c487a2e781.png)
VS

![pico-8 screenshot](https://cloud.githubusercontent.com/assets/49612/9771853/a014ac76-5730-11e5-9584-f1ca44a81edd.png)

**Comment by ftsf** [comment]
@gingerbeardman very strange! I'll try and get to the bottom of this line offset!

I must have missed the equals sign, should be no problem to add.

**Comment by ftsf** [comment]
https://github.com/ftsf/picolove/commit/711297eebf6fdf735d1513a4bd0fd0383fdfd7a0 fixes the missing equals character, and some other missing ones. would you be able to send me the .p8 to test the line issue with?

**Comment by gingerbeardman** [comment]
@ftsf font is fixed, lines are still an issue, plus some transparency issues.

I'll try to create a simpler reduced test case, too.

**Comment by ftsf** [comment]
@gingerbeardman thanks, I think I've fixed it now. You were relying on palt wrapping 16 to 0 which I didn't realised happened, so I've updated that now. https://github.com/ftsf/picolove/commit/0aa66f9b4bbab6174f6f54a6639d4024318e0a52

**Comment by gingerbeardman** [comment]
i didn't realise that either - definitely a bug in my code, what a mess :)

**Comment by ftsf** [comment]
the art is beautiful though! =) marking this resolved!

**Comment by gingerbeardman** [comment]
About the art: thanks!

But the line issue off by 1-pixel is still happening?

**Comment by ftsf** [comment]
Strange, I am unable to reproduce that off by one line issue.

![sidebyside](http://static.impbox.net/kksidebyside.png)

**Comment by gingerbeardman** [comment]
Hmm. Maybe it's a bug in Love2D for Mac?

I'll try on my Windows VM tonight.

**Comment by gingerbeardman** [comment]
So the line offset problem is not present on my old iMac, but is present on my Retina Mac Book Pro.

Retina issue? Love2D bug?

Any thoughts?

**Comment by ftsf** [comment]
This one has got me stumped! Sadly I don't have a retina device to test with. Seems odd that it would make a difference though.

**Comment by Shoozza** [comment]
Is this still happening? @gingerbeardman

**Comment by gingerbeardman** [comment]
I'll check soon

**Comment by gingerbeardman** [comment]
Yes, still happening. 

Using LOVE 0.10.2 with picolove 0.1

I seem to remember a workaround by using 0.5 measures?

<img width="580" alt="screen shot 2019-02-22 at 12 26 26" src="https://user-images.githubusercontent.com/49612/53242613-2a5cc900-369d-11e9-8e87-5256cc687f67.png">

**Comment by gingerbeardman** [comment]
To get this down to raw minimum to reproduce, I have created this test p8 file: 

[test.p8.txt](https://github.com/picolove/picolove/files/2895705/test.p8.txt)

it does the following
- whole screen rectfill to cls 0,0 to 127,127 in light blue to show extent of screen area
- draws 128 horizontal lines of all colours (black, dark blue, purple...) leaving blue edges visible
- uses this code:

```lua
function _draw()
	rectfill(0,0,127,127,12)
	for k = 0,127 do
		color(k%15)
		line(1,k,126,k)
	end
end
```

pico8, correct reference image
![screen shot 2019-02-22 at 20 26 59](https://user-images.githubusercontent.com/49612/53269267-5188ba00-36e0-11e9-961f-7eb5b4213e50.png)

picolove, first line is missing
<img width="580" alt="screen shot 2019-02-22 at 20 26 30" src="https://user-images.githubusercontent.com/49612/53269305-6d8c5b80-36e0-11e9-81ce-2123c9922f3d.png">

can any of you reproduce this?

**Comment by gingerbeardman** [comment]
Also seeing this in my Windows VM, also using love-0-10-2 with picolove 0.1

<img width="596" alt="screen shot 2019-02-22 at 20 42 16" src="https://user-images.githubusercontent.com/49612/53270067-8b5ac000-36e2-11e9-8a34-13f59425ba0a.png">

**Comment by gingerbeardman** [comment]
FWIW 

- current gamax92/picolove does not have this issue running with LOVE 11.2 (yay!)
- an old version of gamax92/picolove, from 9 August 2016, does not have this issue
- an old version of ftfs/picolove, from 8 June 2016, does not have this issue

all of those use `api.lua` which does this sort of thing:

```lua
local function _horizontal_line(lines, x0, y, x1)
	table.insert(lines, {x0+0.5, y+0.5, x1+1.5, y+0.5})
end
```

**Comment by gingerbeardman** [comment]
An old version of picolove I found on my drive, from 8 June 2016, does not have this issue.

**Comment by Shoozza** [comment]
Seems to be fixed
Can you confirm? @gingerbeardman

**Comment by x2nie** [comment]
Its was fixed, I am using picolove 0.1, WIndows 10, love 0.10.2 
![image](https://user-images.githubusercontent.com/1678529/96331294-6d478d80-1086-11eb-8d41-597068839a71.png)

**Comment by Shoozza** [comment]
Closing. Thanks for the review :)
